FROM jfrog.ais.acquia.io/devops-pipeline-prod/acquia/amazonlinux:2023 as argo-rollouts-builder

# Update packages
USER root
RUN yum makecache \
  && yum update -y \
  && yum install -y tar gcc git \
  && yum clean all \
  && rm -rf /var/cache/yum

ARG TARGETOS=linux
ARG TARGETARCH=amd64
# renovate: datasource=golang-version depName=golang packageName=golang versioning=semver
ARG GOLANG_VERSION=1.26.4

# Install Go
RUN echo "Installing Go version ${GOLANG_VERSION}" && \
    curl -LO "https://go.dev/dl/go${GOLANG_VERSION}.${TARGETOS}-${TARGETARCH}.tar.gz" && \
    tar -C /usr/local -xzf "go${GOLANG_VERSION}.${TARGETOS}-${TARGETARCH}.tar.gz" && \
    rm -f "go${GOLANG_VERSION}.${TARGETOS}-${TARGETARCH}.tar.gz" && \
    ls -la /usr/local/go/bin && \
    chmod +x /usr/local/go/bin/go

# Set Golang environment variables
ENV GOPATH="/go"
ENV GOROOT="/usr/local/go"
ENV GOBIN="${GOPATH}/bin"
ENV GO111MODULE="on"
ENV GOOS=${TARGETOS}
ENV GOARCH=${TARGETARCH}
ENV GOPRIVATE=github.com/acquia

# FIPS
ENV GODEBUG='fips140=on'
ENV CGO_ENABLED=1

# Add path to go binaries
ENV PATH="${PATH}:${GOROOT}/bin:${GOBIN}"

ARG ARGO_ROLLOUTS_UPSTREAM=release-1.9

WORKDIR /src

# Fetch upstream source at the specified sha/tag/branch
ADD https://github.com/argoproj/argo-rollouts.git#${ARGO_ROLLOUTS_UPSTREAM} .

COPY . .

ARG MAKE_TARGET="controller-fips"
RUN GOOS=$TARGETOS GOARCH=$TARGETARCH make ${MAKE_TARGET}

#####################################################################################################
## Final image
#####################################################################################################
FROM jfrog.ais.acquia.io/devops-pipeline-prod/acquia/amazonlinux:2023
COPY --from=argo-rollouts-builder /src/dist/rollouts-controller /bin/

USER 999

ENTRYPOINT [ "/bin/rollouts-controller" ]